package application.BBDD;

public class DBQuery {
	public static final String SQL_CONFIGURACIONES =
			" SELECT ID, DES_CONFIGURACION FROM CONFIGURACIONES ";
	
	public static final String SQL_CONFIG_COLORES =
			" SELECT ID_CONFIG, ACCION, COLOR_HEXA, COLOR_HSSF FROM CONFIG_COLORES WHERE ID_CONFIG = ? ";
	
	public static final String SQL_UPDATE_CONFIG_COLORES =
			" UPDATE CONFIG_COLORES SET COLOR_HEXA = ?, COLOR_HSSF = ? WHERE ID_CONFIG = ? AND ACCION = ? ";
	
	public static final String SQL_TABLAS =
			" SELECT ID_CONFIG, PESTAGNA, NOMBRE_TABLA, PK_TABLA, LINEA_COLUMNAS, LINEA_BLOQUEOS, LINEA_DATOS, COLUMNA_DATOS FROM TABLAS WHERE ID_CONFIG = ? ";
	
	public static final String SQL_TABLAS_PESTAGNA =
			" SELECT ID_CONFIG, PESTAGNA, NOMBRE_TABLA, PK_TABLA, LINEA_COLUMNAS, LINEA_BLOQUEOS, LINEA_DATOS, COLUMNA_DATOS FROM TABLAS WHERE ID_CONFIG = ? AND PESTAGNA = ? ";
	
	public static final String SQL_CAMPOS_TIPO =
			" SELECT ID_CONFIG, NOMBRE_TABLA, CAMPO, TIPO FROM CAMPOS_TIPO WHERE ID_CONFIG = ? AND NOMBRE_TABLA = ? ";
	
	public static final String SQL_CAMPO_TIPO =
			" SELECT ID_CONFIG, NOMBRE_TABLA, CAMPO, TIPO FROM CAMPOS_TIPO WHERE ID_CONFIG = ? AND NOMBRE_TABLA = ? AND CAMPO = ? ";
	
	public static final String SQL_BINARIAS =
			" SELECT ID_CONFIG, NOMBRE_TABLA, PESTAGNA, COLUMNA_BINARIA FROM BINARIAS WHERE ID_CONFIG = ? AND NOMBRE_TABLA = ? AND PESTAGNA = ? ";
	
	public static final String SQL_BINARIA =
			" SELECT ID_CONFIG, NOMBRE_TABLA, PESTAGNA, COLUMNA_BINARIA FROM BINARIAS WHERE ID_CONFIG = ? AND NOMBRE_TABLA = ? AND PESTAGNA = ? AND COLUMNA_BINARIA = ? ";
	
	public static final String SQL_SIMPLIFICADAS =
			" SELECT ID_CONFIG, NOMBRE_TABLA, PESTAGNA, COLUMNA_SIMPLIFICADA, COLUMNA FROM DATOS_SIMPLIFICADOS WHERE ID_CONFIG = ? AND NOMBRE_TABLA = ? AND PESTAGNA = ? ";
	
	public static final String SQL_SIMPLIFICADA =
			" SELECT ID_CONFIG, NOMBRE_TABLA, PESTAGNA, COLUMNA_SIMPLIFICADA, COLUMNA FROM DATOS_SIMPLIFICADOS WHERE ID_CONFIG = ? AND NOMBRE_TABLA = ? AND PESTAGNA = ? AND COLUMNA_SIMPLIFICADA = ? ";
	
	public static final String SQL_PARAMETRIZADAS =
			" SELECT ID_CONFIG, NOMBRE_TABLA, PESTAGNA, COLUMNA_PARAMETRIZADA, DATO, TRADUCCION FROM DATOS_PARAMETRIZADOS WHERE ID_CONFIG = ? AND NOMBRE_TABLA = ? AND PESTAGNA = ? ";
	
	public static final String SQL_PARAMETRIZADA =
			" SELECT ID_CONFIG, NOMBRE_TABLA, PESTAGNA, COLUMNA_PARAMETRIZADA, DATO, TRADUCCION FROM DATOS_PARAMETRIZADOS WHERE ID_CONFIG = ? AND NOMBRE_TABLA = ? AND PESTAGNA = ? AND COLUMNA_PARAMETRIZADA = ? ";
	
	public static final String SQL_PARAMETRIZADA_DATO =
			" SELECT ID_CONFIG, NOMBRE_TABLA, PESTAGNA, COLUMNA_PARAMETRIZADA, DATO, TRADUCCION FROM DATOS_PARAMETRIZADOS WHERE ID_CONFIG = ? AND NOMBRE_TABLA = ? AND PESTAGNA = ? AND COLUMNA_PARAMETRIZADA = ? AND DATO = ? ";
	
	public static final String SQL_TRADUCIDAS =
			" SELECT ID_CONFIG, NOMBRE_TABLA, PESTAGNA, COLUMNA_EXCEL, COLUMNA_BBDD FROM TRADUCCIONES WHERE ID_CONFIG = ? AND NOMBRE_TABLA = ? AND PESTAGNA = ? ";
	
	public static final String SQL_TRADUCIDA =
			" SELECT ID_CONFIG, NOMBRE_TABLA, PESTAGNA, COLUMNA_EXCEL, COLUMNA_BBDD FROM TRADUCCIONES WHERE ID_CONFIG = ? AND NOMBRE_TABLA = ? AND PESTAGNA = ? AND COLUMNA_EXCEL = ? ";
	
	public static final String SQL_ACCIONES =
			" SELECT ID_CONFIG, NOMBRE_TABLA, PESTAGNA, ACCION FROM ACCIONES WHERE ID_CONFIG = ? AND NOMBRE_TABLA = ? AND PESTAGNA = ? ";
	
	public static final String SQL_ACCION =
			" SELECT ID_CONFIG, NOMBRE_TABLA, PESTAGNA, ACCION FROM ACCIONES WHERE ID_CONFIG = ? AND NOMBRE_TABLA = ? AND PESTAGNA = ? AND ACCION = ? ";
}
